config/routes.rb
Rails.application.routes.draw do
  root 'home#principal'

  resources :vendors
  resources :rooms
  resources :districts
  resources :zones
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :zone
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :district
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  belongs_to :zone
end

app/models/zone.rb
class Zone < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/districts_controller.rb
class DistrictsController < ApplicationController
  before_action :set_district, only: [:show, :edit, :update, :destroy]

  # GET /districts
  # GET /districts.json
  def index
    @districts = District.all
  end

  # GET /districts/1
  # GET /districts/1.json
  def show
  end

  # GET /districts/new
  def new
    @district = District.new
  end

  # GET /districts/1/edit
  def edit
  end

  # POST /districts
  # POST /districts.json
  def create
    @district = District.new(district_params)

    respond_to do |format|
      if @district.save
        format.html { redirect_to @district, notice: 'District was successfully created.' }
        format.json { render :show, status: :created, location: @district }
      else
        format.html { render :new }
        format.json { render json: @district.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /districts/1
  # PATCH/PUT /districts/1.json
  def update
    respond_to do |format|
      if @district.update(district_params)
        format.html { redirect_to @district, notice: 'District was successfully updated.' }
        format.json { render :show, status: :ok, location: @district }
      else
        format.html { render :edit }
        format.json { render json: @district.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /districts/1
  # DELETE /districts/1.json
  def destroy
    @district.destroy
    respond_to do |format|
      format.html { redirect_to districts_url, notice: 'District was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_district
      @district = District.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def district_params
      params.require(:district).permit(:nombre, :zone_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def principal
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:nombre, :capacidad, :direccion, :contacto_sala, :correo_contacto, :district_id)
    end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:nombre, :apellido, :telefono_movil, :correo, :zone_id)
    end
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  before_action :set_zone, only: [:show, :edit, :update, :destroy]

  # GET /zones
  # GET /zones.json
  def index
    @zones = Zone.all
  end

  # GET /zones/1
  # GET /zones/1.json
  def show
  end

  # GET /zones/new
  def new
    @zone = Zone.new
  end

  # GET /zones/1/edit
  def edit
  end

  # POST /zones
  # POST /zones.json
  def create
    @zone = Zone.new(zone_params)

    respond_to do |format|
      if @zone.save
        format.html { redirect_to @zone, notice: 'Zone was successfully created.' }
        format.json { render :show, status: :created, location: @zone }
      else
        format.html { render :new }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zones/1
  # PATCH/PUT /zones/1.json
  def update
    respond_to do |format|
      if @zone.update(zone_params)
        format.html { redirect_to @zone, notice: 'Zone was successfully updated.' }
        format.json { render :show, status: :ok, location: @zone }
      else
        format.html { render :edit }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zones/1
  # DELETE /zones/1.json
  def destroy
    @zone.destroy
    respond_to do |format|
      format.html { redirect_to zones_url, notice: 'Zone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zone
      @zone = Zone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zone_params
      params.require(:zone).permit(:nombre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/districts/_form.html.erb
<%= simple_form_for(@district) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre %>
    <%= f.association :zone, label_method: :nombre %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/districts/edit.html.erb
<h1>Editando distritos</h1>

<%= render 'form', district: @district %>

<%= link_to 'Show', @district %> |
<%= link_to 'Back', districts_path %>

app/views/districts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Distritos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Zone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @districts.each do |district| %>
      <tr>
        <td><%= district.nombre %></td>
        <td><%= district.zone.nombre %></td>
        <td><%= link_to 'Show', district %></td>
        <td><%= link_to 'Edit', edit_district_path(district) %></td>
        <td><%= link_to 'Destroy', district, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New District', new_district_path %>

app/views/districts/new.html.erb
<h1>Registrar nuevo distrito</h1>

<%= render 'form', district: @district %>

<%= link_to 'Back', districts_path %>

app/views/districts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @district.nombre %>
</p>

<p>
  <strong>Zone:</strong>
  <%= @district.zone.nombre %>
</p>

<%= link_to 'Edit', edit_district_path(@district) %> |
<%= link_to 'Back', districts_path %>

app/views/home/principal.html.erb
<h1>Home#principal</h1>
<h2>Editar página de bienvenida</h2>


<p>Find me in app/views/home/principal.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Salas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= simple_form_for(@room) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre %>
    <%= f.input :capacidad %>
    <%= f.input :direccion %>
    <%= f.input :contacto_sala %>
    <%= f.input :correo_contacto %>
    <%= f.association :district, label_method: :nombre %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Salas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Capacidad</th>
      <th>Direccion</th>
      <th>Contacto sala</th>
      <th>Correo contacto</th>
      <th>Distrito</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.nombre %></td>
        <td><%= room.capacidad %></td>
        <td><%= room.direccion %></td>
        <td><%= room.contacto_sala %></td>
        <td><%= room.correo_contacto %></td>
        <td><%= room.district.nombre %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @room.nombre %>
</p>

<p>
  <strong>Capacidad:</strong>
  <%= @room.capacidad %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @room.direccion %>
</p>

<p>
  <strong>Contacto sala:</strong>
  <%= @room.contacto_sala %>
</p>

<p>
  <strong>Correo contacto:</strong>
  <%= @room.correo_contacto %>
</p>

<p>
  <strong>District:</strong>
  <%= @room.district %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

app/views/vendors/_form.html.erb
<%= simple_form_for(@vendor) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre %>
    <%= f.input :apellido %>
    <%= f.input :telefono_movil %>
    <%= f.input :correo %>
    <%= f.association :zone, label_method: :nombre %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/vendors/edit.html.erb
<h1>Editing Vendor</h1>

<%= render 'form', vendor: @vendor %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Representantes comerciales</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Telefono movil</th>
      <th>Correo</th>
      <th>Zona</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendors.each do |vendor| %>
      <tr>
        <td><%= vendor.nombre %></td>
        <td><%= vendor.apellido %></td>
        <td><%= vendor.telefono_movil %></td>
        <td><%= vendor.correo %></td>
        <td><%= vendor.zone.nombre %></td>
        <td><%= link_to 'Show', vendor %></td>
        <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
        <td><%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vendor', new_vendor_path %>

app/views/vendors/new.html.erb
<h1>New Vendor</h1>

<%= render 'form', vendor: @vendor %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @vendor.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @vendor.apellido %>
</p>

<p>
  <strong>Telefono movil:</strong>
  <%= @vendor.telefono_movil %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @vendor.correo %>
</p>

<p>
  <strong>Zone:</strong>
  <%= @vendor.zone %> 
</p>

<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>

app/views/zones/_form.html.erb
<%= simple_form_for(@zone) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/zones/edit.html.erb
<h1>Editing Zone</h1>

<%= render 'form', zone: @zone %>

<%= link_to 'Show', @zone %> |
<%= link_to 'Back', zones_path %>

app/views/zones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Zonas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zones.each do |zone| %>
      <tr>
        <td><%= zone.nombre %></td>
        <td><%= link_to 'Show', zone %></td>
        <td><%= link_to 'Edit', edit_zone_path(zone) %></td>
        <td><%= link_to 'Destroy', zone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zone', new_zone_path %>

app/views/zones/new.html.erb
<h1>New Zone</h1>

<%= render 'form', zone: @zone %>

<%= link_to 'Back', zones_path %>

app/views/zones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @zone.nombre %>
</p>

<%= link_to 'Edit', edit_zone_path(@zone) %> |
<%= link_to 'Back', zones_path %>